##### 1.Sayılardan oluşan bir boyutlu array oluşturun.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print("Array:", arr1)
print("Boyut:", arr1.ndim) 
print("Şekil:", arr1.shape) 
print("Eleman Sayısı:", arr1.size) 


Array: [1 2 3 4 5]
Boyut: 1
Şekil: (5,)
Eleman Sayısı: 5


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım.

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [3]:
arr2 = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])
arr3 = np.array([[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]])

print("İki boyutlu array:\n", arr2)
print("Boyut:", arr2.ndim)
print("Şekil:", arr2.shape)
print("Eleman Sayısı:", arr2.size)

print("\nÜç boyutlu array:\n", arr3)
print("Boyut:", arr3.ndim)
print("Şekil:", arr3.shape)
print("Eleman Sayısı:", arr3.size)


İki boyutlu array:
 [[1 2 6 7]
 [4 3 9 5]]
Boyut: 2
Şekil: (2, 4)
Eleman Sayısı: 8

Üç boyutlu array:
 [[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyut: 3
Şekil: (2, 2, 3)
Eleman Sayısı: 12


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [9]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
eleman2 = arr2[0,1]
print (eleman2)

2


In [11]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
eleman7 = arr2[0,3]
print(eleman7)

7


In [17]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
eleman9 = arr3[1,1,2]
print (eleman9)

9


In [15]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
eleman5 = arr3[0,0,1]
print (eleman5)

5


##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [19]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
slicing1 = arr2[0, 1:3]
print (slicing1)

[2 6]


In [21]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
slicing2 = arr2[1, 1:]
print (slicing2)

[3 9 5]


In [23]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
slicing3 = arr3[0, 1, :]
print (slicing3)

[21  8 11]


In [25]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
slicing4 = arr3[1, 0, 1:]
print (slicing4)

[ 6 20]
